apiVersion: v1
kind: Service
metadata:
  name: mini-cicd-frontend-service
  namespace: mini-cicd
spec:
  type: ClusterIP
  selector:
    app: mini-cicd-frontend
  ports:
    - port: 80
      targetPort: 80
