all:
  var: 
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    
  children:
    staging:
      hosts:
        staging-server:
          ansible_host: 54.234.80.235
          ansible_user: ubuntu

    prod:
      hosts:
        prod-server:
          ansible_host: 100.52.252.225
          ansible_user: ubuntu
