FROM python:3.11-slim

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    openssh-client \
    git \
    curl \
    && pip install --no-cache-dir ansible \
    && rm -rf /var/lib/apt/lists/*
